### ISSUE TITLE
Performance loss since last update

### ISSUE THREAD

**Issue by louisvangeldrop** [CanadaHonk/porffor#218]
I have compiled quicksort.js to native using "porf native quicksort.js quicksort.exe    --compiler=clang-cl"
Since the last update my quicksort.exe now takes 2063 msec to run. Before the update it was 598 msec

**Comment by CanadaHonk** [comment]
Do you know when or which update specifically affected this?

**Comment by louisvangeldrop** [comment]
Commit:  f52d812

**Comment by CanadaHonk** [comment]
Could you send `quicksort.js` please?

**Comment by louisvangeldrop** [comment]
`
"use strict";
/* This file is modified base on: 
 *  https://browserbench.org/JetStream/wasm/quicksort.c
 */
var SORTELEMENTS = 7281 - 1//7728;
var maximum = 0;
var minimum = 65536;

function initArr(sortList) {
    var seed = 74755;
    for (var i = 1; i <= SORTELEMENTS; i++) {
        sortList[i] = Math.random(seed);
        if (sortList[i] > maximum) {
            maximum = sortList[i];
        }
        else if (sortList[i] < minimum) {
            minimum = sortList[i];
        }
    }
    return sortList;
}

function quickSort(a, l, r) {
    var i = l, j = r;
    var w;
    var idx = Math.floor((l + r) / 2);
    var x = a[idx];
    do {
        while (a[i] < x)
            i++;
        while (x < a[j])
            j--;
        if (i <= j) {
            w = a[i];
            a[i] = a[j];
            a[j] = w;
            i++;
            j--;
        }
    } while (i <= j);
    if (l < j)
        quickSort(a, l, j);
    if (i < r)
        quickSort(a, i, r);
    var print = print ? print : console.log;
}

var print = print ? print : console.log
var performance = performance ? performance : Date

function main(n) {
    var t1 = performance.now();
    // n = 100
    var sortList = new Array(SORTELEMENTS + 1);
    for (var i = 0; i < n; i++) {
        initArr(sortList);
        quickSort(sortList, 1, SORTELEMENTS);
        if (sortList[1] != minimum || sortList[SORTELEMENTS] != maximum) {
            // print('Validate result error in quicksort');
        }
    }
    // print(i)
    print(performance.now() - t1);
}
var n = 1000
main(n)
`

**Comment by Rob23oba** [comment]
Porffor overuses floating-point computation which `-Ofast` can optimize out parts of. However `-O3` won't do most of that because that can violate the floating point standard (e.g. sometimes `(a + b) + c != a + (b + c)`, `-Ofast` pretends they're the same and `-O3` doesn't). In this case specifically it probably compiled `quickSort` to take doubles as parameters which slows down the program significantly.

**Comment by CanadaHonk** [comment]
Ah I didn't spot ` --compiler=clang-cl` in the original comment, yes that is the cause. It adds `-ffast-math` too but only if the compiler argument isn't specified, I'll change how that works.

**Comment by louisvangeldrop** [comment]
Did you already fix this problem? I still notice the same performance loss.

**Comment by CanadaHonk** [comment]
It should have been fixed in the commit above

**Comment by louisvangeldrop** [comment]
I am running version 0.55.24 and still have the performance loss running the quicksort.js example
